version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: antifraude

  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/antifraude

volumes:
  mongo_data:
    driver: local
