name: Build & Deploy to Azure

on:
  push:
    branches: [ "master" ]      # gatilho único para a branch master
  workflow_dispatch:            # permite disparo manual no GitHub UI

env:
  IMAGE_NAME: antifraude        # repositório no ACR
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit & integration tests
        run: ./mvnw -B clean test

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push Docker image
        id: build-image
        run: |
          TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $TAG .
          docker push $TAG
          echo "image=$TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          images: ${{ needs.build-test-push.outputs.image }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
