name: CI - Develop Branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
      kafka:
        image: bitnami/kafka:3
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          ALLOW_PLAINTEXT_LISTENER: "yes"
        ports:
          - 9092:9092

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run Tests
        run: mvn test
